NEWS_TYPES = {
    'https://www.toutiao.com/ch/news_hot/' : '1', # 热点
    'https://www.toutiao.com/ch/news_tech/' : '2', # 科技
    'https://www.toutiao.com/ch/internet/' : '2-1', # 互联网
    'https://www.toutiao.com/ch/software/' : '2-2', # 软件
    'https://www.toutiao.com/ch/smart_home/' : '2-3', # 智能家居
    'https://www.toutiao.com/ch/news_entertainment/' : '3', # 娱乐
    'https://www.toutiao.com/ch/movie/' : '3-1', # 电影
    'https://www.toutiao.com/ch/teleplay/' : '3-2', # 电视剧
    'https://www.toutiao.com/ch/shows/' : '3-3', # 综艺
    'https://www.toutiao.com/ch/gossip/' : '3-4', # 明星八卦
    'https://www.toutiao.com/ch/news_game/' : '4', # 游戏
    'https://www.toutiao.com/ch/news_sports/' : '5', # 体育
    'https://www.toutiao.com/ch/nba/' : '5-1', # NBA
    'https://www.toutiao.com/ch/cba/' : '5-2', # CBA
    'https://www.toutiao.com/ch/csl/' : '5-3', # 中超
    'https://www.toutiao.com/ch/football_italy/' : '5-4', # 意甲
    'https://www.toutiao.com/ch/news_car/' : '6', # 汽车
    'https://www.toutiao.com/ch/car_new_arrival/' : '6-1', # 新车
    'https://www.toutiao.com/ch/suv/' : '6-2', # SUV
    'https://www.toutiao.com/ch/car_guide/' : '6-3', # 汽车导购
    'https://www.toutiao.com/ch/car_usage/' : '6-4', # 用车
    'https://www.toutiao.com/ch/news_finance/' : '7', # 财经
    'https://www.toutiao.com/ch/investment/' : '7-1', # 投资
    'https://www.toutiao.com/ch/stock_channel/' : '7-2', # 股票
    'https://www.toutiao.com/ch/finance_management/' : '7-3', # 理财
    'https://www.toutiao.com/ch/macro_economic/' : '7-4', # 宏观经济
    'https://www.toutiao.com/ch/funny/' : '8', # 搞笑
    'https://www.toutiao.com/ch/news_military/' : '9', # 军事
    'https://www.toutiao.com/ch/military_china/' : '9-1', # 中国军情
    'https://www.toutiao.com/ch/weaponry/' : '9-2', # 武器装备
    'https://www.toutiao.com/ch/military_world/' : '9-3', # 环球军事
    'https://www.toutiao.com/ch/news_world/' : '10', # 国际
    'https://www.toutiao.com/ch/news_fashion/' : '11', # 时尚
    'https://www.toutiao.com/ch/fashion/' : '11-1', # 时装
    'https://www.toutiao.com/ch/body_shaping/' : '11-2', # 美体
    'https://www.toutiao.com/ch/watch/' : '11-3', # 腕表
    'https://www.toutiao.com/ch/jewelry/' : '11-4', # 珠宝
    'https://www.toutiao.com/ch/news_travel/' : '11-5', # 旅游
    'https://www.toutiao.com/ch/news_discovery/' : '12', # 探索
    'https://www.toutiao.com/ch/news_baby/' : '13', # 育儿
    'https://www.toutiao.com/ch/news_regimen/' : '14', # 养生
    'https://www.toutiao.com/ch/news_essay/' : '15', # 美文
    'https://www.toutiao.com/ch/news_history/' : '16', # 历史
    'https://www.toutiao.com/ch/news_food/' : '17', # 美食
}