from models.RepeatUrlConfig import RepeatUrlConfig

REPEAT_URL_CONFIG = set([
    RepeatUrlConfig('https://www.toutiao.com/ch/news_hot/', 1),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_tech/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/internet/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/software/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/smart_home/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_entertainment/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/movie/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/teleplay/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/shows/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/gossip/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_game/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_sports/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/nba/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/cba/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/csl/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/football_italy/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_car/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/car_new_arrival/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/suv/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/car_guide/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/car_usage/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_finance/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/investment/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/stock_channel/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/finance_management/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/macro_economic/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/funny/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_military/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/military_china/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/weaponry/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/military_world/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_world/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_fashion/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/fashion/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/body_shaping/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/watch/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/jewelry/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_travel/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_discovery/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_baby/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_regimen/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_essay/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_history/', 3),
    #RepeatUrlConfig('https://www.toutiao.com/ch/news_food/', 3),
])